#!/usr/bin/env node

/**
 * Interactive script to help set up Supabase environment variables
 */

const fs = require('fs')
const path = require('path')
const readline = require('readline')

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
})

function question(query) {
  return new Promise((resolve) => rl.question(query, resolve))
}

async function setup() {
  console.log('\n🚀 BloomboxAI Environment Setup\n')
  console.log('This script will help you set up your Supabase environment variables.\n')
  console.log('You can find these values at: https://app.supabase.com → Your Project → Settings → API\n')

  const envPath = path.join(__dirname, '..', '.env.local')
  const examplePath = path.join(__dirname, '..', '.env.example')

  // Check if .env.local already exists
  if (fs.existsSync(envPath)) {
    const overwrite = await question('⚠️  .env.local already exists. Overwrite? (y/n): ')
    if (overwrite.toLowerCase() !== 'y') {
      console.log('❌ Setup cancelled.')
      rl.close()
      return
    }
  }

  console.log('\n📝 Enter your Supabase credentials:\n')

  const supabaseUrl = await question('1. NEXT_PUBLIC_SUPABASE_URL (Project URL): ')
  const supabaseAnonKey = await question('2. NEXT_PUBLIC_SUPABASE_ANON_KEY (Anon Key): ')
  const supabaseServiceKey = await question('3. SUPABASE_SERVICE_ROLE_KEY (Service Role Key): ')
  
  // Optional: OpenAI key
  const openaiKey = await question('4. OPENAI_API_KEY (Optional, press Enter to skip): ')

  // Create .env.local content
  let envContent = `# Supabase Configuration
# Generated by setup-env.js on ${new Date().toISOString()}

NEXT_PUBLIC_SUPABASE_URL=${supabaseUrl}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${supabaseAnonKey}
SUPABASE_SERVICE_ROLE_KEY=${supabaseServiceKey}
`

  if (openaiKey.trim()) {
    envContent += `\n# OpenAI Configuration\nOPENAI_API_KEY=${openaiKey}\n`
  }

  // Write to .env.local
  try {
    fs.writeFileSync(envPath, envContent)
    console.log('\n✅ Successfully created .env.local file!\n')
    
    // Verify
    console.log('📋 Summary:')
    console.log(`   ✓ Supabase URL: ${supabaseUrl.substring(0, 30)}...`)
    console.log(`   ✓ Anon Key: ${supabaseAnonKey.substring(0, 20)}...`)
    console.log(`   ✓ Service Key: ${supabaseServiceKey.substring(0, 20)}...`)
    if (openaiKey.trim()) {
      console.log(`   ✓ OpenAI Key: ${openaiKey.substring(0, 20)}...`)
    }
    
    console.log('\n📝 Next steps:')
    console.log('   1. Restart your dev server: npm run dev')
    console.log('   2. Test database connection: npm run test-db')
    console.log('   3. Add these same variables to Vercel for production')
    console.log('\n⚠️  Remember: Never commit .env.local to Git!\n')
    
  } catch (error) {
    console.error('\n❌ Error creating .env.local:', error.message)
  }

  rl.close()
}

setup().catch((error) => {
  console.error('❌ Setup failed:', error)
  rl.close()
  process.exit(1)
})

